In [96]:
import pandas as pd
import logging
#from sqlalchemy import create_engine
import os
from datetime import datetime, timezone

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

In [89]:
file_path = '~/Downloads/example_sales_data.csv'
df_raw = pd.read_csv(file_path)
print(df_raw.head())

         date   store ID          PRODUCT_NAME   quantity     Price  \
0  2023-01-15  Store_005       Laptop Ultra X1        2.0  $1299.99
1   1/16/2023  STORE_005     Desktop PC Gaming        1.0   1499.99
2  2023/01/17  Store_005  Wireless Headphones         3.0    $89.99
3  01-18-2023  store_005        Smartphone X12        NaN    799.99
4  2023-01-19  Store_005            Tablet Pro        0.0    649.99

  customer_type Payment Method Transaction_ID  discount% region
0       Regular            NaN      TRX-45892         0%   West
1       Premium    Credit Card      TRX-45893       0.05   West
2       Regular    Credit Card      TRX-45894          0   West
3       Premier          Debit      TRX-45895        10%   west
4       Regular           Cash      TRX-45896        NaN   WEST

In [90]:
print(df_raw.shape)
print(df_raw.columns)
print(df_raw.dtypes)
print(df_raw.describe(include='all'))

(51, 10)
Index(['date', 'store ID', 'PRODUCT_NAME', ' quantity', 'Price',
       'customer_type', 'Payment Method', 'Transaction_ID', ' discount%',
       'region'],
      dtype='str')
date                  str
store ID              str
PRODUCT_NAME          str
 quantity         float64
Price                 str
customer_type         str
Payment Method        str
Transaction_ID        str
 discount%            str
region                str
dtype: object
              date   store ID     PRODUCT_NAME   quantity   Price  \
count           51         51               51  46.000000      51
unique          51         21               18        NaN      31
top     2023-01-15  Store_005  Laptop Ultra X1        NaN  799.99
freq             1          7                3        NaN       3
mean           NaN        NaN              NaN   2.565217     NaN
std            NaN        NaN              NaN   2.587596     NaN
min            NaN        NaN              NaN   0.000000     NaN
25%            NaN        NaN              NaN   1.000000     NaN
50%            NaN        NaN              NaN   2.000000     NaN
75%            NaN        NaN              NaN   3.000000     NaN
max            NaN        NaN              NaN  15.000000     NaN

       customer_type Payment Method Transaction_ID  discount% region
count             51             47             48         48     51
unique             4              5             48         11     13
top          Regular    Credit Card      TRX-45892         0%   West
freq              30             24              1         15     12
mean             NaN            NaN            NaN        NaN    NaN
std              NaN            NaN            NaN        NaN    NaN
min              NaN            NaN            NaN        NaN    NaN
25%              NaN            NaN            NaN        NaN    NaN
50%              NaN            NaN            NaN        NaN    NaN
75%              NaN            NaN            NaN        NaN    NaN
max              NaN            NaN            NaN        NaN    NaN

In [13]:
print(df_raw.duplicated().sum())

0

In [91]:
#df_raw.columns = [col.strip().lower().replace(' ', '_') for col in df_raw.columns]
df_raw.columns = [col.strip().lower().replace(' ', '_').replace('%', '_pct') for col in df_raw.columns]
print(df_raw.head())

         date   store_id          product_name  quantity     price  \
0  2023-01-15  Store_005       Laptop Ultra X1       2.0  $1299.99
1   1/16/2023  STORE_005     Desktop PC Gaming       1.0   1499.99
2  2023/01/17  Store_005  Wireless Headphones        3.0    $89.99
3  01-18-2023  store_005        Smartphone X12       NaN    799.99
4  2023-01-19  Store_005            Tablet Pro       0.0    649.99

  customer_type payment_method transaction_id discount_pct region
0       Regular            NaN      TRX-45892           0%   West
1       Premium    Credit Card      TRX-45893         0.05   West
2       Regular    Credit Card      TRX-45894            0   West
3       Premier          Debit      TRX-45895          10%   west
4       Regular           Cash      TRX-45896          NaN   WEST

In [26]:
df_raw['sale_date'] = pd.to_datetime(
    df_raw['date'],
    format='mixed',
    errors='coerce',          # Turn unparseable into NaT
    dayfirst=False            # Set True if your data is mostly DD/MM
)

In [27]:
df_raw

,date,store_id,product_name,quantity,price,customer_type,payment_method,transaction_id,discount%,region,sale_date
0,2023-01-15,Store_005,Laptop Ultra X1,2.0,$1299.99,Regular,NaN,TRX-45892,0%,West,2023-01-15
1,1/16/2023,STORE_005,Desktop PC Gaming,1.0,1499.99,Premium,Credit Card,TRX-45893,0.05,West,2023-01-16
2,2023/01/17,Store_005,Wireless Headphones,3.0,$89.99,Regular,Credit Card,TRX-45894,0,West,2023-01-17
3,01-18-2023,store_005,Smartphone X12,NaN,799.99,Premier,Debit,TRX-45895,10%,west,2023-01-18
4,2023-01-19,Store_005,Tablet Pro,0.0,649.99,Regular,Cash,TRX-45896,NaN,WEST,2023-01-19
5,01/20/23,Store_005,USB-C Cable 2m,5.0,$19.99,Regular,Credit Card,NaN,0%,West,2023-01-20
6,2023-01-21,StoreID_005,Wireless Mouse,2.0,$49.99,Regular,Debit Card,TRX-45898,0.00,West,2023-01-21
7,22-01-2023,Store-005,External SSD 1TB,1.0,159.99,Premium,NaN,TRX-45899,5,West,2023-01-22
8,2023-01-23,Store 005,Laptop Stand,4.0,$29.99,Regular,Credit Card,TRX-45900,0,west,2023-01-23
9,1/24/2023,STORE_005,Wireless Keyboard,1.0,79.99,Premier,Credit Card,TRX-45901,15%,West,2023-01-24
10,2023-01-25,Store_005,Power Bank 20000mAh,2.0,$59.99,Regular,Cash,TRX-45902,0%,west,2023-01-25
11,26-Jan-23,Store_005,Bluetooth Speaker,1.0,129.99,Regular,Credit Card,TRX-45903,NaN,West,2023-01-26
12,2023/01/27,Store_005,"Monitor, 27-inch",1.0,349.99,Premium,Debit Card,TRX-45904,10%,West,2023-01-27
13,1/28/2023,Store-005,HDMI Cable,3.0,$14.99,Regular,NaN,TRX-45905,0,West,2023-01-28
14,29.01.2023,Store_005,Wireless Charger,2.0,39.99,Regular,Cash,TRX-45906,0,West,2023-01-29
15,1/30/2023,StoreID_005,Airpods Pro,1.0,na,Premium,Credit Card,TRX-45907,0%,West,2023-01-30
16,2023-1-31,Store 005,Smart Watch Series 7,NaN,299.99,RegularCustomer,Credit Card,TRX-45908,5%,North West,2023-01-31
17,2023-02-01,Store_006,Laptop Ultra X1,1.0,1299.99,Premium,Debit Card,TRX-46001,0,East,2023-02-01
18,02/02/2023,STORE_006,Desktop PC Gaming,2.0,$1499.99,Regular,Credit Card,TRX-46002,10,East,2023-02-02
19,2023/02/03,Store_006,Wireless Headphones,5.0,89.99,Regular,Cash,TRX-46003,NaN,East,2023-02-03
20,2/4/2023,store_006,Smartphone X12,1.0,799.99,Premium,Apple Pay,TRX-46004,0%,east,2023-02-04
21,2023-02-05,Store_006,Tablet Pro,2.0,$649.99,Regular,Credit Card,TRX-46005,5,EAST,2023-02-05
22,6.2.2023,Store_006,USB-C Cable 2m,10.0,19.99,Regular,NaN,TRX-46006,0%,East,2023-06-02
23,2023-02-07,StoreID_006,Wireless Mouse,3.0,$49.99,Premium,Debit Card,TRX-46007,10.0,East,2023-02-07
24,08-02-2023,Store-006,External SSD 1TB,1.0,159.99,Regular,Credit Card,NaN,0%,East,2023-08-02
25,2023-02-09,Store 006,Laptop Stand,2.0,29.99,Regular,Cash,TRX-46009,0,east,2023-02-09
26,2/10/2023,STORE_006,Wireless Keyboard,4.0,$79.99,Premier,Credit Card,TRX-46010,5%,East,2023-02-10
27,2023-02-11,Store_006,Power Bank 20000mAh,1.0,59.99,Regular,Debit Card,TRX-46011,0,East,2023-02-11
28,12-Feb-23,Store_006,Bluetooth Speaker,NaN,129.99,Premium,Credit Card,TRX-46012,0%,East,2023-02-12
29,2023/02/13,Store_006,"Monitor, 27-inch",1.0,$349.99,Regular,Cash,TRX-46013,0%,East,2023-02-13
30,2/14/2023,Store-006,HDMI Cable,5.0,14.99,Regular,Credit Card,TRX-46014,0,east,2023-02-14
31,15.02.2023,Store_006,Wireless Charger,3.0,39.99,Premier,Apple Pay,TRX-46015,10,East,2023-02-15
32,16/02/2023,StoreID_006,Airpods Pro,1.0,249.99,Regular,Credit Card,TRX-46016,0%,East,2023-02-16
33,2023-2-17,Store 006,Smart Watch Series 7,2.0,$299.99,Premium,Debit Card,TRX-46017,5%,North East,2023-02-17
34,2023-02-18,Store_007,Laptop Ultra X1,3.0,1299.99,Regular,Credit Card,TRX-47001,15,South,2023-02-18
35,02/19/2023,STORE_007,Desktop PC Gaming,1.0,$1499.99,Premium,Cash,TRX-47002,0%,South,2023-02-19
36,2023/02/20,Store_007,Wireless Headphones,4.0,89.99,Regular,Credit Card,NaN,0,South,2023-02-20
37,2/21/2023,store_007,Smartphone X12,2.0,799.99,Premier,Debit,TRX-47004,5%,south,2023-02-21
38,2023-02-22,Store_007,Tablet Pro,1.0,$649.99,Regular,Credit Card,TRX-47005,0,SOUTH,2023-02-22
39,23.2.2023,Store_007,USB-C Cable 2m,15.0,19.99,Regular,Cash,TRX-47006,0%,South,2023-02-23
40,2023-02-24,StoreID_007,Wireless Mouse,2.0,$49.99,Premium,Credit Card,TRX-47007,0.05,South,2023-02-24
41,25-02-2023,Store-007,External SSD 1TB,NaN,159.99,Regular,Apple Pay,TRX-47008,0%,South,2023-02-25
42,2023-02-26,Store 007,Laptop Stand,3.0,29.99,Regular,Credit Card,TRX-47009,0,south,2023-02-26
43,2/27/2023,STORE_007,Wireless Keyboard,1.0,$79.99,Premier,Debit Card,TRX-47010,10%,South,2023-02-27
44,2023-02-28,Store_007,Power Bank 20000mAh,2.0,59.99,Regular,Credit Card,TRX-47011,0,South,2023-02-28
45,01-Mar-23,Store_007,Bluetooth Speaker,1.0,Error,Premium,Cash,TRX-47012,0%,South,2023-03-01
46,2023/03/02,Store_007,"Monitor, 27-inch",1.0,$349.99,Regular,Credit Card,TRX-47013,5%,South,2023-03-02
47,3/3/2023,Store-007,HDMI Cable,6.0,14.99,Regular,Debit Card,TRX-47014,0,south,2023-03-03
48,04.03.2023,Store_007,Wireless Charger,NaN,39.99,Premier,Credit Card,TRX-47015,0,South,2023-04-03
49,05/03/2023,StoreID_007,Airpods Pro,2.0,249.99,Regular,Cash,TRX-47016,0%,South,2023-05-03
50,2023-3-06,Store 007,Smart Watch Series 7,1.0,$299.99,Premium,Credit Card,TRX-47017,15%,South East,2023-03-06

In [28]:
date_formats = [
    '%Y-%m-%d', '%m/%d/%Y', '%d/%m/%Y', '%Y/%m/%d',
    '%d-%m-%Y', '%d.%m.%Y', '%d-%b-%Y', '%b-%d-%Y',
    '%d-%b-%y', '%b-%d-%y', '%Y%m%d', '%m-%d-%Y', '%m/%d/%y'
]

def parse_date(x):
    if pd.isna(x):                    # Handle NaN / None early
        return pd.NaT

    x = str(x).strip()
    if x.lower() in ['nan', 'null', '', 'none', 'n/a']:
        return pd.NaT

    for fmt in date_formats:
        try:
            # Return full datetime (best practice)
            return pd.to_datetime(x, format=fmt)
        except:
            continue

    logging.warning(f"Could not parse date: {x}")
    return pd.NaT

In [29]:
df_raw['sale_date'] = df_raw['date'].apply(parse_date)

In [32]:
# 2. Store ID normalization
df_raw['store_id'] = df_raw['store_id'].str.strip().str.upper().str.replace(r'[^0-9]', '', regex=True)

In [34]:
df_raw['store_id'] = df_raw['store_id'].astype('Int64')
df_raw['store_id']

0     5
1     5
2     5
3     5
4     5
5     5
6     5
7     5
8     5
9     5
10    5
11    5
12    5
13    5
14    5
15    5
16    5
17    6
18    6
19    6
20    6
21    6
22    6
23    6
24    6
25    6
26    6
27    6
28    6
29    6
30    6
31    6
32    6
33    6
34    7
35    7
36    7
37    7
38    7
39    7
40    7
41    7
42    7
43    7
44    7
45    7
46    7
47    7
48    7
49    7
50    7
Name: store_id, dtype: Int64

In [36]:
df_raw['product_name'].unique()

<ArrowStringArray>
[     'Laptop Ultra X1',    'Desktop PC Gaming', 'Wireless Headphones ',
       'Smartphone X12',           'Tablet Pro',       'USB-C Cable 2m',
       'Wireless Mouse',     'External SSD 1TB',         'Laptop Stand',
    'Wireless Keyboard',  'Power Bank 20000mAh',    'Bluetooth Speaker',
     'Monitor, 27-inch',           'HDMI Cable',     'Wireless Charger',
          'Airpods Pro', 'Smart Watch Series 7',  'Wireless Headphones']
Length: 18, dtype: str

In [37]:
df_raw['product_name'] = df_raw['product_name'].str.strip().str.replace(r'\s+', ' ', regex=True)

In [38]:
df_raw['product_name'].unique()

<ArrowStringArray>
[     'Laptop Ultra X1',    'Desktop PC Gaming',  'Wireless Headphones',
       'Smartphone X12',           'Tablet Pro',       'USB-C Cable 2m',
       'Wireless Mouse',     'External SSD 1TB',         'Laptop Stand',
    'Wireless Keyboard',  'Power Bank 20000mAh',    'Bluetooth Speaker',
     'Monitor, 27-inch',           'HDMI Cable',     'Wireless Charger',
          'Airpods Pro', 'Smart Watch Series 7']
Length: 17, dtype: str

In [40]:
# 4. Quantity
df_raw['quantity'] = pd.to_numeric(df_raw['quantity'], errors='coerce')
df_raw['quantity'] = df_raw['quantity'].fillna(0).astype(int)

In [41]:
df_raw['quantity']

0      2
1      1
2      3
3      0
4      0
5      5
6      2
7      1
8      4
9      1
10     2
11     1
12     1
13     3
14     2
15     1
16     0
17     1
18     2
19     5
20     1
21     2
22    10
23     3
24     1
25     2
26     4
27     1
28     0
29     1
30     5
31     3
32     1
33     2
34     3
35     1
36     4
37     2
38     1
39    15
40     2
41     0
42     3
43     1
44     2
45     1
46     1
47     6
48     0
49     2
50     1
Name: quantity, dtype: int64

In [43]:
df_raw['price'].unique()

<ArrowStringArray>
['$1299.99',  '1499.99',  ' $89.99',   '799.99',   '649.99',   '$19.99',
   '$49.99',   '159.99',   '$29.99',    '79.99',   '$59.99',   '129.99',
   '349.99',   '$14.99',    '39.99',       'na',   '299.99',  '1299.99',
 '$1499.99',    '89.99',  '$649.99',    '19.99',    '29.99',   '$79.99',
    '59.99',  '$349.99',    '14.99',   '249.99',  '$299.99',   ' 89.99',
    'Error']
Length: 31, dtype: str

In [45]:
# 5. Price
df_raw['price'] = df_raw['price'].astype(str).str.replace(r'[\$,]', '', regex=True).str.strip()
df_raw['price'] = pd.to_numeric(df_raw['price'], errors='coerce')
df_raw['price'].unique()

array([1299.99, 1499.99,   89.99,  799.99,  649.99,   19.99,   49.99,
        159.99,   29.99,   79.99,   59.99,  129.99,  349.99,   14.99,
         39.99,     nan,  299.99,  249.99])

In [47]:
df_raw['discount%'].unique()

<ArrowStringArray>
['0%', '0.05', '0', '10%', nan, '0.00', '5', '15%', '5%', '10', '10.0', '15']
Length: 12, dtype: str

In [ ]:
# 6. Discount
df_raw['discount%'] = df_raw[' discount%'].astype(str).str.replace(r'[%]', '', regex=True).str.strip()
df_raw['discount%'] = pd.to_numeric(df_raw['discount%'], errors='coerce').fillna(0)

In [49]:
import numpy as np

# 6. Normalize Discount Column
def normalize_discount(x):
    if pd.isna(x) or str(x).strip().lower() in ['nan', 'none', '']:
        return 0.0

    x = str(x).strip().replace('%', '').strip()   # Remove % sign

    try:
        val = float(x)

        # If it's a decimal proportion (0 to 1), convert to percentage
        if 0 <= val <= 1:
            val = val * 100

        # Cap at reasonable values (optional but recommended)
        if val < 0:
            return 0.0
        if val > 100:
            return 100.0

        return round(val, 4)   # Keep up to 4 decimals if needed

    except:
        return 0.0


# Apply the function
df_raw['discount_pct'] = df_raw['discount%'].apply(normalize_discount)

In [51]:
df_raw['discount_pct']

0      0.0
1      5.0
2      0.0
3     10.0
4      0.0
5      0.0
6      0.0
7      5.0
8      0.0
9     15.0
10     0.0
11     0.0
12    10.0
13     0.0
14     0.0
15     0.0
16     5.0
17     0.0
18    10.0
19     0.0
20     0.0
21     5.0
22     0.0
23    10.0
24     0.0
25     0.0
26     5.0
27     0.0
28     0.0
29     0.0
30     0.0
31    10.0
32     0.0
33     5.0
34    15.0
35     0.0
36     0.0
37     5.0
38     0.0
39     0.0
40     5.0
41     0.0
42     0.0
43    10.0
44     0.0
45     0.0
46     5.0
47     0.0
48     0.0
49     0.0
50    15.0
Name: discount_pct, dtype: float64

In [53]:
df_raw['customer_type'].str.strip().str.title()

0             Regular
1             Premium
2             Regular
3             Premier
4             Regular
5             Regular
6             Regular
7             Premium
8             Regular
9             Premier
10            Regular
11            Regular
12            Premium
13            Regular
14            Regular
15            Premium
16    Regularcustomer
17            Premium
18            Regular
19            Regular
20            Premium
21            Regular
22            Regular
23            Premium
24            Regular
25            Regular
26            Premier
27            Regular
28            Premium
29            Regular
30            Regular
31            Premier
32            Regular
33            Premium
34            Regular
35            Premium
36            Regular
37            Premier
38            Regular
39            Regular
40            Premium
41            Regular
42            Regular
43            Premier
44            Regular
45            Premium
46            Regular
47            Regular
48            Premier
49            Regular
50            Premium
Name: customer_type, dtype: str

In [75]:
df_raw['region'].unique()

<ArrowStringArray>
['West', 'North West', 'East', 'North East', 'South', 'South East']
Length: 6, dtype: str

In [79]:
# 7. Other fields
df_raw['customer_type'] = df_raw['customer_type'].str.strip().replace('customer', '').str.title().str.replace('Regularcustomer', 'Regular', regex=False).str.replace('Premier', 'Premium', regex=False)
df_raw['payment_method'] = df_raw['payment_method'].fillna('Unknown').str.strip().str.title()
df_raw['transaction_id'] = df_raw['transaction_id'].fillna('UNKNOWN').str.strip().str.upper()
df_raw['region'] = df_raw['region'].str.strip().str.title()

In [73]:
# 7. Customer Type Standardization
def clean_customer_type(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip().title()

    # Apply your rules
    if 'Reg' in x:
        return 'Regular'
    elif 'Pre' in x:
        return 'Premier'

    # Fallback (in case something doesn't match)
    return x


# Apply the function
df_raw['customer_type'] = df_raw['customer_type'].apply(clean_customer_type)

In [82]:
# 8. Derived columns
df_raw['total_amount'] = df_raw['quantity'] * df_raw['price'] * (1 - df_raw['discount_pct']/100)
df_raw['loaded_at'] = datetime.utcnow()

In [97]:
df_raw['loaded_at'] = datetime.now(timezone.utc)

In [85]:

df_raw['total_amount'] = df_raw['total_amount'].fillna(0)
df_raw['total_amount']=df_raw['total_amount'].round(2)
df_raw

,date,store_id,product_name,quantity,price,customer_type,payment_method,transaction_id,discount%,region,sale_date,discount_pct,total_amount,loaded_at
0,2023-01-15,5,Laptop Ultra X1,2,1299.99,Regular,Unknown,TRX-45892,0%,West,2023-01-15,0.0,2599.98,2026-05-07 00:03:12.271195
1,1/16/2023,5,Desktop PC Gaming,1,1499.99,Premium,Credit Card,TRX-45893,0.05,West,2023-01-16,5.0,1424.99,2026-05-07 00:03:12.271195
2,2023/01/17,5,Wireless Headphones,3,89.99,Regular,Credit Card,TRX-45894,0,West,2023-01-17,0.0,269.97,2026-05-07 00:03:12.271195
3,01-18-2023,5,Smartphone X12,0,799.99,Premium,Debit,TRX-45895,10%,West,2023-01-18,10.0,0.00,2026-05-07 00:03:12.271195
4,2023-01-19,5,Tablet Pro,0,649.99,Regular,Cash,TRX-45896,NaN,West,2023-01-19,0.0,0.00,2026-05-07 00:03:12.271195
5,01/20/23,5,USB-C Cable 2m,5,19.99,Regular,Credit Card,UNKNOWN,0%,West,2023-01-20,0.0,99.95,2026-05-07 00:03:12.271195
6,2023-01-21,5,Wireless Mouse,2,49.99,Regular,Debit Card,TRX-45898,0.00,West,2023-01-21,0.0,99.98,2026-05-07 00:03:12.271195
7,22-01-2023,5,External SSD 1TB,1,159.99,Premium,Unknown,TRX-45899,5,West,2023-01-22,5.0,151.99,2026-05-07 00:03:12.271195
8,2023-01-23,5,Laptop Stand,4,29.99,Regular,Credit Card,TRX-45900,0,West,2023-01-23,0.0,119.96,2026-05-07 00:03:12.271195
9,1/24/2023,5,Wireless Keyboard,1,79.99,Premium,Credit Card,TRX-45901,15%,West,2023-01-24,15.0,67.99,2026-05-07 00:03:12.271195
10,2023-01-25,5,Power Bank 20000mAh,2,59.99,Regular,Cash,TRX-45902,0%,West,2023-01-25,0.0,119.98,2026-05-07 00:03:12.271195
11,26-Jan-23,5,Bluetooth Speaker,1,129.99,Regular,Credit Card,TRX-45903,NaN,West,2023-01-26,0.0,129.99,2026-05-07 00:03:12.271195
12,2023/01/27,5,"Monitor, 27-inch",1,349.99,Premium,Debit Card,TRX-45904,10%,West,2023-01-27,10.0,314.99,2026-05-07 00:03:12.271195
13,1/28/2023,5,HDMI Cable,3,14.99,Regular,Unknown,TRX-45905,0,West,2023-01-28,0.0,44.97,2026-05-07 00:03:12.271195
14,29.01.2023,5,Wireless Charger,2,39.99,Regular,Cash,TRX-45906,0,West,2023-01-29,0.0,79.98,2026-05-07 00:03:12.271195
15,1/30/2023,5,Airpods Pro,1,NaN,Premium,Credit Card,TRX-45907,0%,West,2023-01-30,0.0,0.00,2026-05-07 00:03:12.271195
16,2023-1-31,5,Smart Watch Series 7,0,299.99,Regular,Credit Card,TRX-45908,5%,North West,2023-01-31,5.0,0.00,2026-05-07 00:03:12.271195
17,2023-02-01,6,Laptop Ultra X1,1,1299.99,Premium,Debit Card,TRX-46001,0,East,2023-02-01,0.0,1299.99,2026-05-07 00:03:12.271195
18,02/02/2023,6,Desktop PC Gaming,2,1499.99,Regular,Credit Card,TRX-46002,10,East,2023-02-02,10.0,2699.98,2026-05-07 00:03:12.271195
19,2023/02/03,6,Wireless Headphones,5,89.99,Regular,Cash,TRX-46003,NaN,East,2023-02-03,0.0,449.95,2026-05-07 00:03:12.271195
20,2/4/2023,6,Smartphone X12,1,799.99,Premium,Apple Pay,TRX-46004,0%,East,2023-02-04,0.0,799.99,2026-05-07 00:03:12.271195
21,2023-02-05,6,Tablet Pro,2,649.99,Regular,Credit Card,TRX-46005,5,East,2023-02-05,5.0,1234.98,2026-05-07 00:03:12.271195
22,6.2.2023,6,USB-C Cable 2m,10,19.99,Regular,Unknown,TRX-46006,0%,East,2023-02-06,0.0,199.90,2026-05-07 00:03:12.271195
23,2023-02-07,6,Wireless Mouse,3,49.99,Premium,Debit Card,TRX-46007,10.0,East,2023-02-07,10.0,134.97,2026-05-07 00:03:12.271195
24,08-02-2023,6,External SSD 1TB,1,159.99,Regular,Credit Card,UNKNOWN,0%,East,2023-02-08,0.0,159.99,2026-05-07 00:03:12.271195
25,2023-02-09,6,Laptop Stand,2,29.99,Regular,Cash,TRX-46009,0,East,2023-02-09,0.0,59.98,2026-05-07 00:03:12.271195
26,2/10/2023,6,Wireless Keyboard,4,79.99,Premium,Credit Card,TRX-46010,5%,East,2023-02-10,5.0,303.96,2026-05-07 00:03:12.271195
27,2023-02-11,6,Power Bank 20000mAh,1,59.99,Regular,Debit Card,TRX-46011,0,East,2023-02-11,0.0,59.99,2026-05-07 00:03:12.271195
28,12-Feb-23,6,Bluetooth Speaker,0,129.99,Premium,Credit Card,TRX-46012,0%,East,2023-02-12,0.0,0.00,2026-05-07 00:03:12.271195
29,2023/02/13,6,"Monitor, 27-inch",1,349.99,Regular,Cash,TRX-46013,0%,East,2023-02-13,0.0,349.99,2026-05-07 00:03:12.271195
30,2/14/2023,6,HDMI Cable,5,14.99,Regular,Credit Card,TRX-46014,0,East,2023-02-14,0.0,74.95,2026-05-07 00:03:12.271195
31,15.02.2023,6,Wireless Charger,3,39.99,Premium,Apple Pay,TRX-46015,10,East,2023-02-15,10.0,107.97,2026-05-07 00:03:12.271195
32,16/02/2023,6,Airpods Pro,1,249.99,Regular,Credit Card,TRX-46016,0%,East,2023-02-16,0.0,249.99,2026-05-07 00:03:12.271195
33,2023-2-17,6,Smart Watch Series 7,2,299.99,Premium,Debit Card,TRX-46017,5%,North East,2023-02-17,5.0,569.98,2026-05-07 00:03:12.271195
34,2023-02-18,7,Laptop Ultra X1,3,1299.99,Regular,Credit Card,TRX-47001,15,South,2023-02-18,15.0,3314.97,2026-05-07 00:03:12.271195
35,02/19/2023,7,Desktop PC Gaming,1,1499.99,Premium,Cash,TRX-47002,0%,South,2023-02-19,0.0,1499.99,2026-05-07 00:03:12.271195
36,2023/02/20,7,Wireless Headphones,4,89.99,Regular,Credit Card,UNKNOWN,0,South,2023-02-20,0.0,359.96,2026-05-07 00:03:12.271195
37,2/21/2023,7,Smartphone X12,2,799.99,Premium,Debit,TRX-47004,5%,South,2023-02-21,5.0,1519.98,2026-05-07 00:03:12.271195
38,2023-02-22,7,Tablet Pro,1,649.99,Regular,Credit Card,TRX-47005,0,South,2023-02-22,0.0,649.99,2026-05-07 00:03:12.271195
39,23.2.2023,7,USB-C Cable 2m,15,19.99,Regular,Cash,TRX-47006,0%,South,2023-02-23,0.0,299.85,2026-05-07 00:03:12.271195
40,2023-02-24,7,Wireless Mouse,2,49.99,Premium,Credit Card,TRX-47007,0.05,South,2023-02-24,5.0,94.98,2026-05-07 00:03:12.271195
41,25-02-2023,7,External SSD 1TB,0,159.99,Regular,Apple Pay,TRX-47008,0%,South,2023-02-25,0.0,0.00,2026-05-07 00:03:12.271195
42,2023-02-26,7,Laptop Stand,3,29.99,Regular,Credit Card,TRX-47009,0,South,2023-02-26,0.0,89.97,2026-05-07 00:03:12.271195
43,2/27/2023,7,Wireless Keyboard,1,79.99,Premium,Debit Card,TRX-47010,10%,South,2023-02-27,10.0,71.99,2026-05-07 00:03:12.271195
44,2023-02-28,7,Power Bank 20000mAh,2,59.99,Regular,Credit Card,TRX-47011,0,South,2023-02-28,0.0,119.98,2026-05-07 00:03:12.271195
45,01-Mar-23,7,Bluetooth Speaker,1,NaN,Premium,Cash,TRX-47012,0%,South,2023-03-01,0.0,0.00,2026-05-07 00:03:12.271195
46,2023/03/02,7,"Monitor, 27-inch",1,349.99,Regular,Credit Card,TRX-47013,5%,South,2023-03-02,5.0,332.49,2026-05-07 00:03:12.271195
47,3/3/2023,7,HDMI Cable,6,14.99,Regular,Debit Card,TRX-47014,0,South,2023-03-03,0.0,89.94,2026-05-07 00:03:12.271195
48,04.03.2023,7,Wireless Charger,0,39.99,Premium,Credit Card,TRX-47015,0,South,2023-03-04,0.0,0.00,2026-05-07 00:03:12.271195
49,05/03/2023,7,Airpods Pro,2,249.99,Regular,Cash,TRX-47016,0%,South,2023-05-03,0.0,499.98,2026-05-07 00:03:12.271195
50,2023-3-06,7,Smart Watch Series 7,1,299.99,Premium,Credit Card,TRX-47017,15%,South East,2023-03-06,15.0,254.99,2026-05-07 00:03:12.271195

In [86]:
explain:

SyntaxError: invalid syntax (2927112033.py, line 1)

In [ ]:
def load_to_postgres(df: pd.DataFrame):
    conn_str = f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
    engine = create_engine(conn_str)

    try:
        with engine.connect() as conn:
            conn.execute("CREATE SCHEMA IF NOT EXISTS raw;")
            conn.execute("CREATE SCHEMA IF NOT EXISTS analytics;")

        df.to_sql('sales_raw', engine, schema='raw', if_exists='replace', index=False)
        logging.info(f"✅ Loaded {len(df)} cleaned rows into raw.sales_raw")

        # Validation
        with engine.connect() as conn:
            count = conn.execute("SELECT COUNT(*) FROM raw.sales_raw").scalar()
            logging.info(f"Validation: {count} rows loaded")

            nulls = conn.execute("""
                SELECT COUNT(*) FROM raw.sales_raw
                WHERE sale_date IS NULL OR price IS NULL OR quantity < 0
            """).scalar()
            if nulls > 0:
                logging.warning(f"⚠️ Found {nulls} rows with critical nulls")

    except Exception as e:
        logging.error(f"❌ Load failed: {e}")
        raise